import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:fluttertoast/fluttertoast.dart';
import '../../core/app_export.dart';
import '../presentation/successful_screen/successful_screen.dart';
import '../widgets/app_bar/appbar_image_1.dart';
import '../widgets/app_bar/appbar_title.dart';
import '../widgets/app_bar/custom_app_bar.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    PrefUtils().setThemeData(_newTheme);
    Get.forceAppUpdate();
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      useMaterial3: true,
      bottomSheetTheme: BottomSheetThemeData(backgroundColor: appTheme.whiteA700,surfaceTintColor: appTheme.whiteA700),
      dialogTheme: DialogThemeData(backgroundColor: appTheme.white,
      surfaceTintColor: appTheme.white),
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: colorScheme.onErrorContainer,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: colorScheme.primary,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      radioTheme: RadioThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      checkboxTheme: CheckboxThemeData(
        fillColor: MaterialStateColor.resolveWith((states) {
          if (states.contains(MaterialState.selected)) {
            return colorScheme.primary;
          }
          return colorScheme.onSurface;
        }),
        side: BorderSide(
          width: 1,
        ),
        visualDensity: const VisualDensity(
          vertical: -4,
          horizontal: -4,
        ),
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.gray200,
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.black900,
          fontSize: 16.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: appTheme.black900,
          fontSize: 14.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w400,
        ),
        displaySmall: TextStyle(
          color: appTheme.black900,
          fontSize: 34.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w700,
        ),
        headlineMedium: TextStyle(
          color: appTheme.black900,
          fontSize: 28.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w700,
        ),
        headlineSmall: TextStyle(
          color: appTheme.black900,
          fontSize: 24.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w700,
        ),
        titleLarge: TextStyle(
          color: appTheme.black900,
          fontSize: 22.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w700,
        ),
        titleMedium: TextStyle(
          color: appTheme.black900,
          fontSize: 18.fSize,
          fontFamily: 'Open Sans',
          fontWeight: FontWeight.w700,
        ),
        titleSmall: TextStyle(
          color: colorScheme.onPrimaryContainer,
          fontSize: 14.fSize,
          fontFamily: 'Urbanist',
          fontWeight: FontWeight.w500,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF132C4E),
    primaryContainer: Color(0XFF29ACF4),
    secondary: Color(0XFF29ACF4),
    secondaryContainer: Color(0XFF132C4E),
    tertiary: Color(0XFF29ACF4),
    tertiaryContainer: Color(0XFF132C4E),

    // Background colors
    background: Color(0XFF29ACF4),

    // Surface colors
    surface: Color(0XFF29ACF4),
    surfaceTint: Color(0XFFE7E7E8),
    surfaceVariant: Color(0XFF132C4E),

    // Error colors
    error: Color(0XFFE7E7E8),
    errorContainer: Color(0XFF682E70),
    onError: Color(0XFF132C4E),
    onErrorContainer: Color(0XFFFFFFFF),

    // On colors(text colors)
    onBackground: Color(0XFF212121),
    onInverseSurface: Color(0XFF132C4E),
    onPrimary: Color(0XFFE7E7E8),
    onPrimaryContainer: Color(0XFF212121),
    onSecondary: Color(0XFF212121),
    onSecondaryContainer: Color(0XFFE7E7E8),
    onTertiary: Color(0XFF212121),
    onTertiaryContainer: Color(0XFFE7E7E8),

    // Other colors
    outline: Color(0XFFE7E7E8),
    outlineVariant: Color(0XFF29ACF4),
    scrim: Color(0XFF29ACF4),
    shadow: Color(0XFFE7E7E8),

    // Inverse colors
    inversePrimary: Color(0XFF29ACF4),
    inverseSurface: Color(0XFFE7E7E8),

    // Pending colors
    onSurface: Color(0XFF212121),
    onSurfaceVariant: Color(0XFFE7E7E8),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber500 => Color(0XFFFFC107);
  Color get amber700 => Color(0XFFF6A202);

  // Black
  Color get black900 => Color(0XFF000000);

  //buttonColor
  Color get buttonColor => Color(0XFF132C4E);

  // BlueGray
  Color get blueGray100 => Color(0XFFD6D6D6);
  Color get blueGray200 => Color(0XFFB0C8C1);
  Color get blueGray300 => Color(0XFF829EBD);
  Color get blueGray400 => Color(0XFF888888);
  Color get blueGray500 => Color(0XFF6E65A1);
  Color get blueGray700 => Color(0XFF455A64);

  // DeepPurple
  Color get deepPurple50 => Color(0XFFE5D1FF);

  // Gray
  Color get gray100 => Color(0XFFEEF2FB);
  Color get gray10001 => Color(0XFFF4F3F3);
  Color get gray10002 => Color(0XFFF7F7F7);
  Color get gray200 => Color(0XFFEDEDED);
  Color get gray300 => Color(0XFFE0E0E0);
  Color get gray400 => Color(0XFFB9B9B9);
  Color get gray50 => Color(0XFFFAFAFA);
  Color get gray700 => Color(0XFF696969);
  Color get gray70001 => Color(0XFF616161);
  Color get gray800 => Color(0XFF533916);
  Color get gray80001 => Color(0XFF383E41);
  Color get gray30 => Color(0XFFD7D7D7);
  Color get lightGray => Color(0XFFF8F8F8);

  // Green
  Color get green50 => Color(0XFFD9F3DF);
  Color get greenA700 => Color(0XFF009C49);

  // Indigo
  Color get indigo400 => Color(0XFF5C6BC0);
  Color get indigo900 => Color(0XFF21246E);
  Color get indigo90001 => Color(0XFF0E336A);
  Color get indigo90002 => Color(0XFF002987);

  // LightBlue
  Color get lightBlue600 => Color(0XFF039BE5);
  Color get lightblue => Color(0XFFEEF3FC);

  // LightGreen
  Color get lightGreen200 => Color(0XFFD1D9B5);
  Color get lightGreen500 => Color(0XFF9CAF4F);


  // Lime
  Color get lime900 => Color(0XFF6E741C);

  // Orange
  Color get orange50 => Color(0XFFFFE9D1);

  // Pink
  Color get pink50 => Color(0XFFFFD1E6);
  Color get pink700 => Color(0XFFAF4F5B);

  // Red
  Color get red100 => Color(0XFFFFD1D1);
  Color get red600 => Color(0XFFE53935);
  Color get red60001 => Color(0XFFDD3333);

  // Teal
  Color get teal300 => Color(0XFF4FAFA3);
  Color get teal30001 => Color(0XFF40B0BE);
  Color get teal50 => Color(0XFFD9F1F4);
  Color get teal900 => Color(0XFF003E59);

  // White
  Color get whiteA700 => Color(0XFFFEFEFE);
  Color get white => Color(0XFFFFFFFF);
  Color get blue => Color(0XFF132C4E);

  // Yellow
  Color get yellow900 => Color(0XFFD97B23);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
closeApp() {
  Future.delayed(const Duration(milliseconds: 1000), () {
    SystemNavigator.pop();
  });
}
getDownloadDialogue(context,function){
  return showDialog(
    barrierDismissible: false,
    context: context,
    builder: (context) {
      return AlertDialog(
          insetPadding: EdgeInsets.all(16),
          shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(20)),
          contentPadding: EdgeInsets.zero,
          content: SuccessfulScreen(function: (){},));
    },
  );
}

getImageUploadMethod(function,title){
  return Padding(
    padding:  EdgeInsets.only(left: 20.h,right: 20.h,top: 24.v),
    child: GestureDetector(
      onTap: function,
      child: Container(
        width: double.infinity,
        padding: EdgeInsets.symmetric(
          horizontal: 78.h,
          vertical: 145.v,
        ),
        decoration:
        AppDecoration.fillGray10002.copyWith(
          borderRadius:
          BorderRadiusStyle.roundedBorder8,
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            CustomImageView(
              svgPath: ImageConstant.imgUpload,
              height: 50.adaptSize,
              width: 50.adaptSize,
            ),
            SizedBox(height: 10.v),
            Text(
              title,
              style: CustomTextStyles
                  .titleMediumOnPrimaryContainer,
            ),
          ],
        ),
      ),
    ),
  );
}


getCustomToast(text){
  return Fluttertoast.showToast(
      msg: text,
      toastLength: Toast.LENGTH_SHORT,
      gravity: ToastGravity.CENTER,
      timeInSecForIosWeb: 1,
      backgroundColor: Colors.red,
      textColor: Colors.white,
      fontSize: 16.fSize
  );
}

Widget getCommonAppBar(title,{leadingFunction,actionWidget}){
  return Container(
      padding: EdgeInsets.symmetric(vertical: 17.v),
      decoration: AppDecoration.outlineGray,
      child: Column(mainAxisSize: MainAxisSize.min, children: [
        SizedBox(height: 6.v),

        CustomAppBar(
            leadingWidth: 44.h,
            leading: AppbarImage1(
                svgPath: ImageConstant.imgArrowleft,
                margin: EdgeInsets.only(top: 3.v, bottom: 5.v),
                onTap:leadingFunction?? () {
                  Get.back();
                }),
            title: AppbarTitle(
                text: title,
                margin: EdgeInsets.only(left: 16.h)),
        actions: [
         Padding(padding: EdgeInsets.only(right: 20.h),
         child:  actionWidget??SizedBox(),)
        ],)

      ]));
}