// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTwJc24_jqSQ_Q3H8y8ToOv7e4WcrGHvA',
    appId: '1:692713078513:web:27f764b0b1db2d3910b350',
    messagingSenderId: '692713078513',
    projectId: 'building-guard-app',
    authDomain: 'building-guard-app.firebaseapp.com',
    databaseURL: 'https://building-guard-app-default-rtdb.firebaseio.com',
    storageBucket: 'building-guard-app.firebasestorage.app',
    measurementId: 'G-59CV1ZXY5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA7ZMbuPBNlAmRMhtJ4jZgCq5Qy2gr8ag',
    appId: '1:692713078513:android:15938858244927f110b350',
    messagingSenderId: '692713078513',
    projectId: 'building-guard-app',
    databaseURL: 'https://building-guard-app-default-rtdb.firebaseio.com',
    storageBucket: 'building-guard-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0MIDrNPrlgmpOY2u8PNZ9JhfcrdgMgLM',
    appId: '1:692713078513:ios:4dbb5373bc51e35c10b350',
    messagingSenderId: '692713078513',
    projectId: 'building-guard-app',
    databaseURL: 'https://building-guard-app-default-rtdb.firebaseio.com',
    storageBucket: 'building-guard-app.firebasestorage.app',
    iosBundleId: 'com.aiimagegenerator.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0MIDrNPrlgmpOY2u8PNZ9JhfcrdgMgLM',
    appId: '1:692713078513:ios:4dbb5373bc51e35c10b350',
    messagingSenderId: '692713078513',
    projectId: 'building-guard-app',
    databaseURL: 'https://building-guard-app-default-rtdb.firebaseio.com',
    storageBucket: 'building-guard-app.firebasestorage.app',
    iosBundleId: 'com.aiimagegenerator.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTwJc24_jqSQ_Q3H8y8ToOv7e4WcrGHvA',
    appId: '1:692713078513:web:ca09f0d22e6311c010b350',
    messagingSenderId: '692713078513',
    projectId: 'building-guard-app',
    authDomain: 'building-guard-app.firebaseapp.com',
    databaseURL: 'https://building-guard-app-default-rtdb.firebaseio.com',
    storageBucket: 'building-guard-app.firebasestorage.app',
    measurementId: 'G-MST6E8C4BF',
  );
}
