import 'controller/finalize_nine_controller.dart';import 'package:ai_image_generator/core/app_export.dart';import 'package:ai_image_generator/widgets/app_bar/appbar_button_7.dart';import 'package:ai_image_generator/widgets/app_bar/custom_app_bar.dart';import 'package:ai_image_generator/widgets/custom_elevated_button.dart';import 'package:ai_image_generator/widgets/custom_outlined_button.dart';import 'package:ai_image_generator/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class FinalizeNineScreen extends GetWidget<FinalizeNineController> {const FinalizeNineScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [Container(padding: EdgeInsets.symmetric(vertical: 17.v), decoration: AppDecoration.outlineGray, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 6.v), CustomAppBar(title: AppbarButton7(margin: EdgeInsets.only(left: 20.h), onTap: () {onTapFinalize();}))])), Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 24.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgIllustrationha244x244, height: 374.adaptSize, width: 374.adaptSize, radius: BorderRadius.circular(8.h)), SizedBox(height: 26.v), Text("lbl_add_title".tr, style: theme.textTheme.titleMedium), SizedBox(height: 18.v), CustomTextFormField(controller: controller.himselfWhileActController, hintText: "msg_himself_while_acting".tr, textInputAction: TextInputAction.done), SizedBox(height: 5.v)]))])), bottomNavigationBar: Container(margin: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 24.v), decoration: AppDecoration.white, child: Container(decoration: AppDecoration.white, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomOutlinedButton(width: 173.h, text: "lbl_share".tr), CustomElevatedButton(width: 177.h, text: "lbl_download".tr)]))))); } 
/// Navigates to the editThreeScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the editThreeScreen.
onTapFinalize() { Get.toNamed(AppRoutes.editThreeScreen, ); } 
 }
