import 'controller/finalize_one_controller.dart';import 'package:ai_image_generator/core/app_export.dart';import 'package:ai_image_generator/widgets/app_bar/appbar_image_1.dart';import 'package:ai_image_generator/widgets/app_bar/appbar_title.dart';import 'package:ai_image_generator/widgets/app_bar/custom_app_bar.dart';import 'package:ai_image_generator/widgets/custom_elevated_button.dart';import 'package:ai_image_generator/widgets/custom_outlined_button.dart';import 'package:ai_image_generator/widgets/custom_switch.dart';import 'package:ai_image_generator/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class FinalizeOneScreen extends GetWidget<FinalizeOneController> {const FinalizeOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [Container(padding: EdgeInsets.symmetric(vertical: 17.v), decoration: AppDecoration.outlineGray, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 6.v), CustomAppBar(leadingWidth: 44.h, leading: AppbarImage1(svgPath: ImageConstant.imgArrowleft, margin: EdgeInsets.only(left: 20.h, top: 4.v, bottom: 4.v), onTap: () {onTapArrowleftone();}), title: AppbarTitle(text: "lbl_finalize".tr, margin: EdgeInsets.only(left: 16.h)))])), SizedBox(height: 16.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgIllustrationha244x244, height: 374.adaptSize, width: 374.adaptSize, radius: BorderRadius.circular(8.h)), SizedBox(height: 26.v), Text("lbl_add_title".tr, style: theme.textTheme.titleMedium), SizedBox(height: 18.v), CustomTextFormField(controller: controller.actionBeautyfulController, hintText: "msg_beautyful_man_ai".tr, textInputAction: TextInputAction.done), SizedBox(height: 24.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 5.v), child: Text("msg_show_nagative_prompt".tr, style: theme.textTheme.titleMedium)), Obx(() => CustomSwitch(value: controller.isSelectedSwitch.value, onChange: (value) {controller.isSelectedSwitch.value = value;}))]), SizedBox(height: 16.v), Container(width: 374.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 13.v), decoration: AppDecoration.fillGray10002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Container(width: 331.h, margin: EdgeInsets.only(top: 3.v, right: 10.h), child: Text("msg_this_cute_symbol".tr, maxLines: 3, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyLarge!.copyWith(height: 1.50))))]))))])), bottomNavigationBar: Container(margin: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 24.v), decoration: AppDecoration.white, child: Container(decoration: AppDecoration.white, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomOutlinedButton(width: 173.h, text: "lbl_share".tr), CustomElevatedButton(width: 177.h, text: "lbl_download".tr)]))))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
